name: Deploy to PyPI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine bumpver

    - name: Extract version
      id: get_version
      run: |
        echo "PACKAGE_VERSION=$(bumpver show | grep -oP 'Current Version: \K.*')" >> $GITHUB_ENV        

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload -r testpypi dist/*

    - name: Notify Discord
      if: success()
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      run: |
        curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"A new release v$PACKAGE_VERSION has been uploaded to PyPI: [Check it out!](https://test.pypi.org/project/CalcPy/)\"}" $DISCORD_WEBHOOK_URL
